# GPT
gpt_3.5_turbo: "gpt-3.5-turbo-0125" # 16K
gpt_4_turbo: "gpt-4-0125-preview" # 128K

# Embedding
embedding_model_small: "text-embedding-3-small"
embedding_model_large: "text-embedding-3-large"

# Whisper
# tiny base small medium large
model_name: "small"

# Google
